# Generated by Django 5.0.1 on 2024-01-01 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Optional name for this scan session", max_length=255
                    ),
                ),
                (
                    "source_path",
                    models.CharField(help_text="Path to the scanned directory", max_length=1024),
                ),
                (
                    "recursive",
                    models.BooleanField(
                        default=True, help_text="Whether subdirectories were scanned"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scanning", "Scanning"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_files_found", models.PositiveIntegerField(default=0)),
                ("total_files_processed", models.PositiveIntegerField(default=0)),
                ("total_files_failed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Scan Session",
                "verbose_name_plural": "Scan Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MusicFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(help_text="Full path to the file", max_length=1024)),
                ("filename", models.CharField(help_text="Filename without path", max_length=512)),
                ("title", models.CharField(blank=True, db_index=True, max_length=512)),
                ("artist", models.CharField(blank=True, db_index=True, max_length=512)),
                ("album", models.CharField(blank=True, max_length=512)),
                ("isrc", models.CharField(blank=True, max_length=20, verbose_name="ISRC")),
                ("genre", models.CharField(blank=True, max_length=255)),
                ("year", models.CharField(blank=True, max_length=10)),
                (
                    "duration",
                    models.PositiveIntegerField(default=0, help_text="Duration in seconds"),
                ),
                ("processed", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "scan_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_files",
                        to="scanner.scansession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Music File",
                "verbose_name_plural": "Music Files",
                "ordering": ["artist", "album", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="musicfile",
            index=models.Index(
                fields=["scan_session", "artist", "album"], name="scanner_mus_scan_se_8a3ccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="musicfile",
            index=models.Index(fields=["title", "artist"], name="scanner_mus_title_c10c20_idx"),
        ),
    ]
