# Generated by Django 5.0.14 on 2026-02-28 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="musicfile",
            new_name="scanner_mus_scan_se_b4d8a6_idx",
            old_name="scanner_mus_scan_se_8a3ccf_idx",
        ),
        migrations.RenameIndex(
            model_name="musicfile",
            new_name="scanner_mus_title_3d0097_idx",
            old_name="scanner_mus_title_c10c20_idx",
        ),
        migrations.AlterField(
            model_name="musicfile",
            name="album",
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="musicfile",
            name="duration",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Duration in seconds",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
