# Generated by Django 5.0.1 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format_type', models.CharField(choices=[('csv', 'CSV (Soundiiz)'), ('json', 'JSON'), ('m3u', 'M3U Playlist'), ('txt', 'TXT (Simple Text)')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='playlists.playlist')),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
