name: CI Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      UV_PROJECT_ENVIRONMENT: .venv
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Sync dependencies
        run: |
          uv venv
          uv sync --extra dev --frozen
      - name: Run tests
        run: |
          uv run pytest --cov=src/musiclist_for_soundiiz --cov-report=term-missing --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
